// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr4f40s3KDGfJXmqmjnFPZdphNAZCd8ig',
    appId: '1:980470502548:web:99ade54406dcb047579081',
    messagingSenderId: '980470502548',
    projectId: 'donghua-app1',
    authDomain: 'donghua-app1.firebaseapp.com',
    storageBucket: 'donghua-app1.firebasestorage.app',
    measurementId: 'G-4BKKDWFXTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwlnTNhDSmGy8ujj1e237OkzfBsrxJCuU',
    appId: '1:980470502548:android:23e9343f0b606781579081',
    messagingSenderId: '980470502548',
    projectId: 'donghua-app1',
    storageBucket: 'donghua-app1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9zmMlwIvpPFhayVNMjBAUi-O9kJ7cAkg',
    appId: '1:980470502548:ios:9ad62d7974776a29579081',
    messagingSenderId: '980470502548',
    projectId: 'donghua-app1',
    storageBucket: 'donghua-app1.firebasestorage.app',
    iosBundleId: 'com.example.donghuaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9zmMlwIvpPFhayVNMjBAUi-O9kJ7cAkg',
    appId: '1:980470502548:ios:9ad62d7974776a29579081',
    messagingSenderId: '980470502548',
    projectId: 'donghua-app1',
    storageBucket: 'donghua-app1.firebasestorage.app',
    iosBundleId: 'com.example.donghuaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr4f40s3KDGfJXmqmjnFPZdphNAZCd8ig',
    appId: '1:980470502548:web:13584cb4b6f077a1579081',
    messagingSenderId: '980470502548',
    projectId: 'donghua-app1',
    authDomain: 'donghua-app1.firebaseapp.com',
    storageBucket: 'donghua-app1.firebasestorage.app',
    measurementId: 'G-DE9FQ0XCNP',
  );
}
